server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: netcool
    key-store-type: PKCS12
    key-alias: mylocalcert

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: forms-service
          uri: http://localhost:8081
          predicates:
            - Path=/forms/**
        - id: emails-service
          uri: http://localhost:8082
          predicates:
            - Path=/emails/**